name = "tabsessionsaver-cloudsync"
main = "src/index.js"
compatibility_date = "2026-07-12"

[[d1_databases]]
binding = "DB"
database_name = "tabsessionsaver-sync"
database_id = "1c5d216a-fbaf-4199-990b-734ca0b0d7bf"
